---
title: "My first dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)

knitr::opts_chunk$set(
	echo = FALSE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))

library(plotly)
```


```{r}
data("rest_inspec")
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r, fig.width = 10}
rest_inspec %>% 
  separate(inspection_date, 
           into = c("year", "month", "date"), 
           sep = "\\-", 
           remove = FALSE) %>% 
  filter(grade %in% c("A", "B", "C"),
         lubridate::year(inspection_date) %in% 2013:2017,
         str_detect(inspection_type, "Initial") == FALSE,
         score > 0) %>% 
  group_by(year) %>% 
  mutate(
    count = n()
  ) %>% 
  filter(grade == "A") %>% 
  mutate(
    count_a = n()) %>% 
  distinct(count, count_a) %>% 
  summarize(
    a_rate = round(count_a/count*100, digits = 2)
  ) %>% 
  plot_ly(x = ~year, y = ~a_rate, type = "scatter", mode = "marker") %>% 
  layout(xaxis =
           list(
             title = "Year"
           ),
         yaxis =
           list(
             title = "'A' Grades as a Percent of Grades"
           ))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
rest_inspec %>% 
  filter(!is.na(violation_code)) %>% 
  group_by(dba) %>% 
  summarize(
    count = n()) %>%
  filter(count > 500) %>% 
  mutate(dba =
           as.factor(dba),
         dba = 
           fct_reorder(dba, count)) %>% 
  plot_ly(x = ~dba, y = ~count, type = "bar") %>% 
  layout(xaxis =
           list(
             title = "Business"
           ),
         yaxis =
           list(
             title = "Number of Violations (2013-2017)"
           ))  
```

### Chart C

```{r}
rest_inspec %>% 
  mutate(
    year = lubridate::year(inspection_date),
    boro =
      as.factor(boro)
  ) %>% 
  filter(year %in% 2013:2017,
         grade %in% c("A", "B", "C"),
         !is.na(score),
         boro != "Missing") %>%
  group_by(boro) %>% 
  plot_ly(x = ~boro, y = ~score, type = "box")
```

